# Generated by Django 4.0.2 on 2022-03-02 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_image_alter_blog_date_alter_blog_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tag', verbose_name='My Tags'),
        ),
    ]
