# Generated by Django 4.0.2 on 2022-03-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='home.Tag', verbose_name='My Tags'),
        ),
    ]
