# Generated by Django 4.0.2 on 2022-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_blog_tags_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, related_name='tagss', to='home.Tag', verbose_name='MyTags'),
        ),
    ]
