# Generated by Django 4.0.2 on 2022-07-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESTADMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
