# Generated by Django 4.0 on 2021-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_data',
            fields=[
                ('image_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.TextField()),
                ('image_username', models.TextField()),
                ('image_user_base_id', models.IntegerField()),
                ('image_is_downloaded', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.TextField(default='null'),
        ),
    ]
