# Generated by Django 4.0 on 2021-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_data',
            name='image_path',
            field=models.FileField(upload_to=''),
        ),
    ]
