# Generated by Django 2.2.12 on 2022-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartEyeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FileField(upload_to='')),
                ('image_encoded', models.TextField()),
                ('image_username', models.TextField()),
                ('image_user_base_id', models.IntegerField()),
                ('image_is_downloaded', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
