# Generated by Django 2.2.12 on 2022-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteye', '0002_facedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='image_path',
            field=models.FileField(upload_to='images/'),
        ),
    ]
